<?php

namespace Daken\ReleaseProfilerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DatabaseQueryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatabaseQueryRepository extends EntityRepository
{
}
